import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        sans: ["DM Sans", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Cascadia Code", "monospace"],
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      colors: {
        "on-tertiary-fixed-variant": "#004c69",
        "primary": "#b4c5ff",
        "on-primary-fixed-variant": "#003ea8",
        "on-tertiary": "#00354a",
        "tertiary": "#7bd0ff",
        "surface-container": "#171f33",
        "on-surface": "#dae2fd",
        "tertiary-fixed-dim": "#7bd0ff",
        "tertiary-container": "#00759f",
        "outline": "#8d90a0",
        "on-background": "#dae2fd",
        "error": "#ffb4ab",
        "secondary-fixed-dim": "#4edea3",
        "secondary-fixed": "#6ffbbe",
        "on-error": "#690005",
        "surface": "#0b1326",
        "on-surface-variant": "#c3c6d7",
        "on-secondary-fixed": "#002113",
        "primary-fixed": "#dbe1ff",
        "primary-container": "#2563eb",
        "secondary": "#4edea3",
        "on-secondary-fixed-variant": "#005236",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#2d3449",
        "outline-variant": "#434655",
        "on-primary": "#002a78",
        "surface-container-lowest": "#060e20",
        "background": "#0b1326",
        "on-secondary-container": "#00311f",
        "on-tertiary-container": "#e1f2ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed": "#001e2c",
        "surface-variant": "#2d3449",
        "surface-tint": "#b4c5ff",
        "on-primary-fixed": "#00174b",
        "surface-container-low": "#131b2e",
        "inverse-surface": "#dae2fd",
        "secondary-container": "#00a572",
        "on-primary-container": "#eeefff",
        "surface-container-high": "#222a3d",
        "surface-bright": "#31394d",
        "on-secondary": "#003824",
        "inverse-on-surface": "#283044",
        "surface-dim": "#0b1326",
        "inverse-primary": "#0053db",
        "error-container": "#93000a",
        "tertiary-fixed": "#c4e7ff",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        status: {
          pending: "hsl(var(--status-pending))",
          active: "hsl(var(--status-active))",
          completed: "hsl(var(--status-completed))",
          overdue: "hsl(var(--status-overdue))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "calc(var(--radius) + 4px)",
        "2xl": "calc(var(--radius) + 8px)",
      },
      boxShadow: {
        card: "0 1px 3px rgba(0,0,0,0.3), 0 1px 2px rgba(0,0,0,0.2)",
        "card-hover": "0 4px 20px rgba(0,0,0,0.4), 0 1px 4px rgba(0,0,0,0.2)",
        "glow-primary": "0 0 24px hsl(var(--primary) / 0.3), 0 0 8px hsl(var(--primary) / 0.2)",
        "glow-secondary": "0 0 24px hsl(var(--secondary) / 0.3)",
        "inner-border": "inset 0 1px 0 rgba(255,255,255,0.05)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-up": {
          from: { opacity: "0", transform: "translateY(14px)", filter: "blur(4px)" },
          to: { opacity: "1", transform: "translateY(0)", filter: "blur(0)" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "slide-in-left": {
          from: { opacity: "0", transform: "translateX(-16px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-up": "fade-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) both",
        "fade-in": "fade-in 0.4s ease both",
        shimmer: "shimmer 1.4s ease infinite",
        "slide-in-left": "slide-in-left 0.5s cubic-bezier(0.16, 1, 0.3, 1) both",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
